import StoreInitializer from "@/components/StoreInitializer";
import { useCart } from "@/store/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetching cart data of user from server
  const dataRes = await fetch("http://localhost:3001/cart");
  const data = await dataRes.json();

  return (
    <html lang="en">
      {/* Passing down the data from server to client so we can manage it using zustand */}
      <StoreInitializer CartItems={data} />
      <body>{children}</body>
    </html>
  );
}
