import { useCart } from "@/store/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const dataRes = await fetch("http://localhost:3001/products");
  const data = await dataRes.json();

  useCart.setState({ products: data });

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
